# Shared by every machine. Machine-specific packages live in Brewfile.<machine>.
# `chezmoi apply` runs `brew bundle` on this file plus the matching one whenever either changes.

tap "oven-sh/bun"
tap "athevon/tokeneater"

# CLI tools
brew "alass"
brew "automake"
brew "awscli"
brew "bat"
brew "oven-sh/bun/bun"
brew "ccextractor"
brew "chezmoi"
brew "cloudflared"
brew "coreutils"
brew "dovi_tool"
brew "exiftool"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-tar"
brew "htop"
brew "just"
brew "libtool"
brew "libuv"
brew "mas"
brew "media-info"
brew "micro"
brew "mkvtoolnix"
brew "nvm"
brew "openjdk"
brew "pipx"
brew "postgresql@18"
brew "pyenv"
brew "shellcheck"
brew "tesseract-lang"
brew "uv"
brew "wget"
brew "zinit"

# Casks
cask "1password"
cask "1password-cli"
cask "aegisub"
cask "beekeeper-studio"
cask "betterdisplay"
cask "claude-code"
cask "cursor"
cask "docker-desktop"
cask "drivedx"
cask "elmedia-player"
cask "firefox"
cask "font-maven-pro"
cask "font-meslo-lg-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "istat-menus"
cask "iterm2" # still the terminal in daily use; drop once the move to Ghostty sticks
cask "logi-options+"
cask "makemkv"
cask "mkvtoolnix-app"
cask "namechanger"
cask "notion"
cask "plex"
cask "postman"
cask "rar"
cask "raycast"
cask "sublime-text"
cask "the-unarchiver"
cask "tokeneater"
cask "transmission"
cask "transmit"
cask "whatsapp"

# Mac App Store
mas "BetterSnapTool", id: 417375580
mas "DaisyDisk", id: 411643860
mas "Fantastical - Calendar & Tasks", id: 975937182
mas "hide.me VPN", id: 953040671
mas "Subtitle Extractor", id: 876111075
