# CLI Tools
brew "automake"
brew "awscli"
brew "bat"
brew "chezmoi"
brew "coreutils"
brew "exiftool"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-tar"
brew "htop"
brew "libtool"
brew "libuv"
brew "mas"
brew "media-info"
brew "micro"
brew "nvm"
brew "openjdk"
brew "pipx"
brew "pyenv"
brew "tesseract-lang"
brew "uv"
brew "wget"
brew "zinit"

# Casks
cask "1password-cli"
cask "aegisub"
cask "betterdisplay"
cask "claude-code"
cask "cursor"
cask "docker-desktop"
cask "drivedx"
cask "elmedia-player"
cask "firefox"
cask "font-maven-pro"
cask "font-meslo-lg-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "istat-menus"
cask "jdownloader"
cask "logi-options+"
cask "makemkv"
cask "mkvtoolnix-app"
cask "namechanger"
cask "notion"
cask "plex"
cask "postman"
cask "rar"
cask "raycast"
cask "sublime-text"
cask "the-unarchiver"
cask "transmission"
cask "transmit"
cask "whatsapp"
cask "zoom"

# Mac App Store
mas "BetterSnapTool", id: 417375580
mas "DaisyDisk", id: 411643860
mas "Fantastical - Calendar & Tasks", id: 975937182
mas "hide.me VPN", id: 953040671
mas "Subtitle Extractor", id: 876111075
